version: '3'

services:
  apache_php:
    build: .
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:11.1.3-jammy
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: composer
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1q2w3e4r

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
